### ISSUE TITLE
[deepcam][data loading] Use of NVIDIA DALI with Deepcam

### ISSUE THREAD

**Issue by BTMichalowicz** [mlcommons/hpc#24]
Hi! I'm currently fiddling around with the deepcam benchmark and plan on using NVIDIA DALI on the deepcam dataset. Right now, I'm using [this script](https://github.com/davidmascharka/tbd-nets/blob/master/utils/h5_to_np.py) to convert the .h5 files to .npy, as DALI does not currently support HDF5 (see https://github.com/NVIDIA/DALI/issues/1252). 

Are there any better/more efficient ways to deal with this? Thank you in advance.

**Comment by azrael417** [comment]
Hello,

A conversion script is here 

https://github.com/mlcommons/hpc_results_v1.0/blob/master/NVIDIA/benchmarks/deepcam/implementations/pytorch/src/utils/convert_hdf52npy.py

And the corresponding Dali pipeline (along with an overall optimized benchmark) is here:

https://github.com/mlcommons/hpc_results_v1.0/tree/master/NVIDIA/benchmarks/deepcam/implementations/pytorch/src/deepCam/data

There are a few variants for numpy datasets, with and without manual caching. Just pick whatever works best for you.

Best
Thorsten

**Comment by BTMichalowicz** [comment]
Awesome. Thank you so much!
