### ISSUE TITLE
Update to rev 1.0

### ISSUE THREAD

**Issue by azrael417** [mlcommons/hpc#4]
Dear Sir/madam,

can we please update the repo to v1.0:

https://github.com/azrael417/mlperf-deepcam/tree/mlperf-hpc-v1.0

I think the best would be to not using sub-repos but instead pull and push it into mlcommons repo. Please let me know if you need my help.

Best regards
Thorsten

**Comment by sparticlesteve** [comment]
@memani1 for now updated the link, but I agree we should put the code in directly: https://github.com/mlcommons/hpc/pull/5
